== Glosalist 2003
:revdate: 2018-11-30

// XXX REMARK -- New message:
................................................................
To: glosalist{at}lists{dot}zeta{dot}org{dot}au
Subject: Re: [glosalist] Interview with Wendy Ashby
From: Robin Gaskell <rgaskell{at}zeta{dot}org{dot}au>
Date: Sun, 29 Dec 2002 21:38:49 +1100

At 10:53 AM 12/20/02 -0800, Charles wrote:
>>[Marcel] Sorry, I am late, my letter was from May the 5th and her from June
>
>I am used to Latin-American time, which runs 3 hours late,
>but this 6 month lag is truly impressive ...
>
*  Better late than never.  ~Es ma boni te es tardi, de nuli-tem.~

>> WA: "vi plu simi".
>
>> Si konfusi es posi Hogben e Ron pa uti "plu simi de tu".
>> Mu ma amo u-ci kausa "plu" veni imedia pre "simi".
>
>> plu persona freqe ma amo brevi id e evita "de" etc.
>
*  Not much context given.  What was Wendy referring to: what was the
English equivalent?
      ' ... your apes ... '
      ' ... the apes of you(rs) ... '
      ' ... apes o'you ... '

>She is correct in placement of the possessive/genitive.
>Here you have 2 noun phrases combined with or without a
>particle. Each can be singular or plural, independently.
*  I like example; otherwise the abstract is too abstract for me.
  
>Clearest usage invokes the particle DE (and/or SU) to
>separate the possessor from the possessed, but in the
>real-world, people often elide it, leaving ambiguity.
>So "tu simi" could be either insulting or not depending
>on context; re-inserting a SU or ES would disambiguate.
*  Still none the wiser without examples of full sentences using these words.

>(SU is just my suggestion for a new particle to be the
>reverse of DE, i.e. the so-called Saxon genitive.)
*  [not of] ?
   What is a Saxon genetive, please?
   When proposing an addition to the lexicon, it is likely to be more
widely accepted if you give Glosa example including it in sentences with
English translation.


>But she suggests "fe bovi" as a natural elision; most
>of the world would prefer "bovi fe" (from elided DE).
>
*  female bovine  -->  femina bovi
                  --> u fe bovi   (abbreviation) [= cow]
                  -->  fe-bovi     (alternate)

   This is in line with my understanding of the production of Glosa
compounds; elision hardly?


  ~U ju-fe pa veni te gene lakti ex u fe-bovi.~

  "The girl went to milk the cow."

  cf
  ~U ju-fe pa veni te gene lakti ex plu bovi.~  (elision)

  "The girl went to milk the cattle."

  and
  ~U ju-fe pa veni te gene lakti ex fe fe-bovi.~

  "The girl went to milk her cow."

  but
  ~U ju-fe pa veni te gene lakti ex fe plu fe-bovi.~

  "The girl went to milk her cows."

 
   
>> Si tu ne amo "sto" posi tu ma amo:
>> "tena se" = restrain myself
>
>I consider the STI and STO of Hogben completely bogus.
>TENA is better, 
*  ~Sti~ and ~Sto~ break the "similarity rule.  It is a cute duo, but these
opposites vary by only one letter, and could cause accidents - if people
mis-heard instructions about the use of moving machinery.
   True, alternatives like ~tena~ give more semantic colour, but the ~st+~
twins work well if accompanied by redundancy.
  ~Sto id, te sekti u flu.~   [Stop it to cut the flow.]

  ~Sti id nu, kausa id ki.~   [Turn it on now: make it (to) go.] 

but then I'd want 100% bisyllabic roots.
>(Words like KONFUSI and IMEDIA also appear bogus to me.)
>The truest Glosa has a self-consistency beyond authority.
>
*  Obviously, the Indo-European based Glosa is quite a different language
from the a priori language Charles suggests.
   What is self-consistent beyond human authority: perhaps the universal
language of thought?

Saluta,  

Robin Gaskell


---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: glosalist{at}lists{dot}zeta{dot}org{dot}au
Subject: Re: [glosalist] Interview with Wendy Ashby
From: Robin Gaskell <rgaskell{at}zeta{dot}org{dot}au>
Date: Mon, 30 Dec 2002 00:25:07 +1100

At 11:41 AM 12/20/02 +0100, Marcel Springer wrote:
>
>  ...  The questions mainly belong to Glosalist discussions in the
>first half of the year 2002.
>
>Mi volu; vi habe hedo Kristo-nati-tem, boni fini de paleo anua e
>sani, paci e boni-fortuna 2003!  Marcel.
>
*  Gracia.

>   .....
>In inter-reti na diskusi de u loka de "possessive pronoun".
>
>In classical Glosa the possessive pronoun seems to come before
>u(n)/plu:  mi plu vagona - my cars.  Some people in internet (me too)
>rather would like to put it after it.
>
*  The question, as I see it, is which has more semantic strength, the
possessive pronoun or the counter?  
  IE   somebody's   one/more  cow

    In this case I feel that, logically, the function of the pers.pron is
of a lower order than the discriminating noun indicator.  Add this idea to
the one that says "a word is modified by its precedent", and then consider
a phrase from the 'head final' structure point of view.
    If all this does mean that words build up in significance in a phrase,
then, in the case of the possessive 'abstraction' "somebody's" is less
discriminating that the 'number abstraction' "one or more."

>  ...  A noun phrase then always would start
>  with a (mandatory) u(n)/plu, the main concept word (noun) comes last
*  So far so good.

>  and all attributes - adjectives, genitives, participles and also the
>  possessive pronoun - would come between.
*  In general, the determinant/NOUN_PHRASE_marker comes first, but there is
some sort of logic which asks are some categories of 'modifier' external to
the main phrase, and I believe that the possessive is one of these.

>- A noun phrase could be easier acknowledged, when it starts with
>  u(n)/plu.
>- Appositions: "Mi ne amo plu vi simi - I do not like your apes." /
>  "... vi plu simi - ... you apes"
>
*  Is it  %you umpteen ape%  or  %umpteen you ape%?  I'd say that the
former, of these, is in line with the Glosa syntax pattern.

>Nick contradicts with the example "u fe bovi - a (female) cow,
>fe u bovi - her cow", but this does not convince me (could be
>"fe-bovi").  Also I do not think, that there could be confusions with
>u-mi, u-tu etc.
>
>Perhaps you can explain, why it must (or only should?) be like this?
>
*  I'd say that the hyphenated compound, ~fe-bovi~ is always a "cow."
   Also, when the possessed category is in the singular, IE "cow" not
"cows," then the correct thinking is to see the poss.pers.pron and the
number_marker particle as alternatives, probably mutually exclusive.
   If it's a straight, singular phrase then ~u~ is in; but, if the NOUN is
possessed, then the poss.pers.pron is used as an alternative NOUN PHRASE
indicator, EG
  ~U fe-bovi greso longo u via.~    "The cow walks along the road."

  ~Fe bovi greso longo u via.~      "Her bovine walks along the road."

  Of course, were it necessary to differentiate between her bull and her
cow, then we have to get out of 'elision mode,' so we'd know if ^it's
Arthur or Martha^.
   Thus:-
 ~Fe fe-bovi greso longo u via.~    "Her cow walks along the road." AND

 ~Fe an-bovi greso longo u via.~    "Her bull walks along the road."

>WA: "vi plu simi".  Plu kron "plu" es no-nece.  "vi" es ma de mo.
>    "vi simi" es sati.
*  But, when the man is distributing one ape to Fred, and a number of apes
to Jon, the he might say:-
   ~Fred, ci es tu simi; e Jon, tu plu simi es la.~

>    Hogben e Ron pa uti "plu tu simi" = your apes (mo persona e ma de
>    mo simi).
*  Although Lancelot and Ronald have the reputations, I have to suggest
that the PLU modifies the SIMI, and does not modify the TU: it is as if the
~tu~ is outside the brackets, while the monkeys, ~plu simi~, are inside it.
 In fact, we can say that the ~tu~ modifies (owns) both the ~plu~ and the
~simi~.

>    Si konfusi es posi Hogben e Ron pa uti "plu simi de tu".  Mu ma
>    amo u-ci kausa "plu" veni imedia pre "simi".  Na zero kron pa dice
>    de muta u-ci sistema.
*  By half closing your eyes, you can see the brackets around "the apes",
with the possessive placed either in front of the leading brace, or after
the closing brace: the ~de~ can be seen as functioning as the closing brace.
IE               tu (plu simi)    =    (plu simi) tu

>    Freqe "u/un" e "plu" es no-nece.  Exempla:
>    mo bibli -, tri bibli -, poli bibli -, oligo bibli -, zero bibli
>    es epi tabla.
>
>    Fe-bovi = cow, female ox
>    bovi-fe = cow-girl
>    fe bovi alo bovi de fe = her cow.
*  OK!
>
>[I find this question very important!!!  I understood,
>  "'u(n)/plu' - possessive pronoun - noun"
>is okay, but prefereable, if the sentence is not too long, is
>  "'u(n)/plu' - noun - 'de' - possessive pronoun".]
>
*   There is an obvious case for being able to abstract the syntax from the
words ... using some form of symbols for the different grammatical functions.
EG # (noun)  ....................  girl, cow  :  ju-fe, fe-bovi
   #-#  (compound noun)  ........  cow-girl, girl-cow  : bovi-fe
   #'    (possessive noun)  .....  cow's, girl's :  de u fe-bovi, ju-fe
   .  (determinant/noun-marker) ..  a, the     :     u
   &     (plural) ................       's    :    plu
   0     (personal pronoun)  .....      she, him, us  : fe, an, na
   @  (Possessive personal pronoun) ....  her, his, our : fe, an, na
   _    [combined functions]        ....     
   |     (conjunction)      ............     of       :    de   

@ #          her cow          :  fe fe-bovi               @ #
@ #_&        her cows         :  fe plu fe-bovi           @ ._& #  
. #-#' #  the cow-girl's cows : plu fe-bovi de u bovi-fe  ._& # | . #-#  
. #_& | 0   the cows for him  : plu fe-bovi pro an        ._& # | 0
. # | @     the cow of hers   : u fe-bovi de fe           . # | @
. #-#_&' #_&  the cow-girls' cows  :
                          plu fe-bovi de plu bovi-fe   ._& #-# | ._& #    

     More work needed, but you see what I mean.

Saluta,

Robin
  P.S.  And I never got onto nested possessives either, 
         EG  The cow-girls' cows' bull.  
                            (But sex has no part in a show like this.)    


---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: glosalist{at}lists{dot}zeta{dot}org{dot}au
Subject: Re: [glosalist] Interview with Wendy Ashby
From: Robin Gaskell <rgaskell{at}zeta{dot}org{dot}au>
Date: Mon, 30 Dec 2002 00:52:47 +1100

At 11:41 AM 12/20/02 +0100, Marcel wrote:
>
>Here there are some questions I asked Wendy Ashby and her answers.
>
> - - - - -  Much cropped
>
>solidarity
>==========
>
>Qo es Glosa verba pro "solidarity" e "solidary"?  Qe, posi "solidari"
>alo in 1000 simpli "akorda"?
>
>WA: Pende ex kontextu, exampla: tu pote uti
>      komuni akorda
>      lega akorda, etc.
>
>    Solidarity es Français lexi.  Itera kontextu es gravi.
>    Plu exempla:
>      komuni akti
>      kon ergo
>      ergo kon alelo ko komuni fide
>
>[Unfortunately no direct "solidarity".
>In Glosa Inter-reti Diktionaria:
>"komuni akorda  solidarity; solidary" item added.
>"lega akorda  solidarity; solidary" item added.
>"komuni akti  solidarity; solidary" item added.
>"kon ergo  solidarity; solidary" item added.
>"komuni fide  solidarity; solidary" item added.]
>
*  This looks like a case where the abstract noun has stretched so widely
that it cannot have a word-for-word direct translation.  It would seem that
Wendy has called in the auxilliaries, and has produced compound nouns, or
what we could call, in English, "phrasal nouns."
   This appears to be a new category among word groupings, such that the
translator must choose from a family of related compound nouns the right
one for the instance he or she is translating.

Saluta,

Robin


---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Subject: [glosalist] New Year
From: "Alexander E. Kirpichev" <brickswall{at}mtu-net.ru>
Date: Wed, 1 Jan 2003 02:57:19 +0300

Dear friends,
Now, it is already the year 2003 in my country, though it is still the 2002,
e.g. in the UK and the USA!

I was not very active glosa-pe during the second half of the year, but
believe me, my heart was always with you!

Excuse me for letters, I have not answered yet! I know that the months
passed, but I was (and I am still) so busy.

Mi fu responde a plu grama, in bi fu meno; ka mi fu habe vakatio, meno-bi.

Happy New Year, dear friends, plu karo glosa-be.

I want the year to be the begining of the peace-and-tolerance-age in the
world and hearts of all humans on the Earth!

Saluta,
Alex


---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: glosalist{at}lists{dot}zeta{dot}org{dot}au
Subject: Re: [glosalist] New Year
From: Sydpidd{at}aol{dot}com
Date: Wed, 1 Jan 2003 10:07:19 EST

time has cought up with us!
happy new year to all in 2003 and eventually all the other laggards
sid

---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: glosalist{at}lists{dot}zeta{dot}org{dot}au
Subject: Re: [glosalist] dictionary updated
From: Robin Gaskell <rgaskell{at}zeta{dot}org{dot}au>
Date: Thu, 02 Jan 2003 12:23:39 +1100

At 11:37 AM 12/20/02 +0100, Marcel wrote:
>
>The Glosa-dictionary on http://www.glosa.org/gid/ has been updated.
>
>
>I have compared the word list of the book "Français - Glosa 1000" 
>with the Glosa Internet Dictionary.  Result:
>
>241 corrections or little changes were made to the French list.
>    (Mostly missing French accents and wrong "Similar Synonyms".
>     Files:
>      http://www.glosa.org/gid/frgl1ko.htm  - old, original list,
>      http://www.glosa.org/gid/frgl1k.htm   - new, corrected list,
>      http://www.glosa.org/gid/gl1kfr.htm   - corrected list, >
                                               reversed,
>      http://www.glosa.org/gid/frglcorr.htm - protocol of changes)
>
>And about 1000 (!) additions/little changes/corrections were made 
>    .......
             AND
>    .......
I am happy, that the dictionary has made another advance, but it can
be seen, that there is a far way to go, yet:  So many changes only
by comparison with one little list!  It would be good to have a
detailed look at the list "Deutsch - Glosa 1000" as well, I think.
>
Excellent work Marcel,
   This consistency - or at least of being as consistent as the various
language/cultures will allow - of a Planned Language across the spectrum of
National Languages, is one of the unspoken problems in  auxilliary language
discussion.
   I did print out the 144 pages of the GID Eng-->Glo dictionary - most
probably the  frgl1ko.htm  list.  Perhaps I should now print out the
gl1kfr.htm  list: I must look. 
   What do your mnemonics mean: I remember best if I understand what I am
trying to place in memory, 
  EG fr-gl-l-k-o  French to Glosa list(GID) knitted in OK.  (?) 
    or
     gl-l-k-fr  Glosa list(GID) now_inKluding French    (??)   ;-) 

   But being serious, again, I would ask what length the <gllkan> file
(Glosa list(GID) inKluding ALL national_languages) might be; and, when will
it be put together by our unpaid volunteers - mainly you, Marcel?

   There are two other serious questions: the first involves 'criteria' for
addition, or creation, of new words for an evergrowing Glosa GID lexicon;
and and the second is by what mechanism, and in what format, will such a
<gllka-05> file be published (Glosa list[GID] inKluding ALL words
adopted_by_2005)?  I am looking into the future, and suggesting that a
Glosa dictionary should carry the year of production in its name, and I
might anticipate that we could have such a list completed by 2005.   For
example, I currently use  _Glosa 6000(1992)_  and the  GID(2/9/02)
[.../gid/engl.htm].  

   We cannot wait until the language is perfected before getting some form
of "international" dictionary out into general circulation; and, we cannot
wait for Wendy's health, and finances, to improve sufficiently, before we
publish an 'authorised' Glosa World Dictionary (or "Glosa Munda Diktionari").

   I know there are already two Glosa usage communities, the hard-copy
based Third-worlders (mainly Africans), and the Internet-connected
'globals.'  This causes a few problems, but the implication is that the two
should not be allowed to separate too far; and, that any GID ought to be
paper-printable in some form.  For postage reasons I think of the extremely
flimsy "war-time paper."

  This returns me to the theme of decisions.  Do we have a core of people
who are reasonably satisfied with the original Ron Clark conception of
Glosa (circa 1992), to form a "Trustee Group" that can oversee the
application of criteria concerning the addition of new words; and, which
can authorise, and ensure, the publication - in various forms - of accepted
standard dictionaries of Glosa.
  Unfortunately, the latter requirement of such 'trustees' involves the
economic question of the actual printing of paper books, booklets and
lists.  Without a practical centralisation of authority, we will continue
to have non-matching dictionaries and a quandry over what is, and is not,
Glosa.  So, Wendy runs the Glosa Education Organisation charity, and hold
the funds; but how are these funds being employed in furthering education
in, and teaching of, Glosa.
  I have avoided for years any though of becoming more dominant in the
Glosa saga, but Marcel's prognosis has prompted me to make these
suggestions.  It does lokk like there will be a 'Burning Bush' in the
Middle East before there is an authorised  _Glosa 2500 Learners'
Dictionary_.  However, I feel we should see what we have to offer the
world, and get it ready in usable form asap.
 
  Very simply, I was going to go through the old GID, and select from it
the 250 most functional words, to make up the Learners' Dictionary.
>From numerous earlier discussions, the dictionary size of 2500 - 3000
words came up as a workable, practical compromise between the ease of
learning, and the ability to communicate meaningfully.
  I suspect that the extra words that Marcel has included in the <frgllk>
file will not be very significant in the compilation of a shorter
dictionary for learners: the question of size/weight/postage is more
important at the lower end of the dictionary scale, than is the matter of
completeness.
  I ask again for URLs to minimum word lists, but I am probably being lazy,
and ought to be able to find them by typing something into Google.  The
lists I would peruse are in the range 2000 to 5000 words.
 
  And while, people CAN look up words by turning on their computers,
calling up the file, and skimming through it, ... a printed dictionary is
infinitely quicker.  And, in the fast-food era, we are also in the time of
fast-learning, and almost instantly-learnt auxlangs.

  Glosa can deliver on this latter, as Ron was oft wont to say: he claimed
that a Classical scholar, once the ground-rules of Glosa were laid out
before them, could start speaking in fairly accurate Glosa almost instantly
- calling upon their knowlege of Greek and Latin roots.  So, I put the case
that economically printable dictionaries ought not be excluded from our
Glosa "Trustees'" wish-list.  With better format, wore words fit onto a
page; with thinner paper, postage prices are less; and the marginal
learner, who is attracted to a small book he can buy for, say A$15 (incl
p&p), might find having to download files, and print them out, might be
just that bit more irksome.
   Anyone know of a source of low-cost, preferably opaque and strong,
air-mail paper?

Saluta,

Robin Gaskell
  P.S.  I hope that everyone is thinking about the article they are going
to write, in Glosa, to submit for the next Plu Glosa Nota.  Mine will be
about the recent drought and bush-fires, here in Australia.  And don't
forget: the reader wants to know your thoughts and feelings as well as the
facts.  While Glosa stands by its reputation as being a language for
science, it is in the minds of the people that the battle will be won, or
lost.  We need to EMOTE people through the colour of our language, and from
the strength of the emotion we convey.   "Wow: if a designed language can
have such communication power built into it, I'd better learn it."     R.


---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Subject: Re: [glosalist] dictionary updated
From: "Marcel Springer" <marcel{at}mspringer{dot}de>
Date: Thu, 2 Jan 2003 12:00:14 +0100


Karo Robin,

Tu grafo, 2003-01-02:
 > What do your mnemonics mean: I remember best if I understand what I
 > am trying to place in memory,
 >  EG fr-gl-l-k-o  French to Glosa list(GID) knitted in OK.  (?)
 >     or
 >    gl-l-k-fr  Glosa list(GID) now_inKluding French    (??)   ;-)

The thing I call GID (Glosa Internet Dictionary or Glosa Inter-reti
Diktionaria) is http://www.glosa.org/gid/glen.txt (gl=Glosa to
en=English).

GID is the project once started by you (Robin), Paul Bartlett and Bill
Patterson.

There are some other files in the www.glosa.org/gid directory, which
are directly compiled from this file by computer algorithms, so they
must not have contradictions to glen.txt:
  glen.htm (HTML-Version), engl.txt (en=English to gl=Glosa),
  engl.htm, coglen.htm (only most useful Glosa-words, co=Core) and
  coengl.htm.

Please do not mix them up with the French files:
frgl1ko.htm is the fr=French to gl1k=Glosa1000 o=original list by
  Ashby/Clark.
frgl1k.htm is same list, but with corrections (no "o" for original),
and gl1kfr.htm is the reversed corrected list, Glosa-French.
None of these three lists are a translation of GID!  GID is more
comprehensive and better!



 >    There are two other serious questions: the first involves
 > 'criteria' for addition, or creation, of new words for an
 > evergrowing Glosa GID lexicon; ...

I would like a GID that ...
- includes all existing Glosa word lists by Ashby/Clark.
- supplements (as few as possible) missing words, which are not in the
    Richmond-lists, but which are needed for communication.
- clears up errors and inconsistencies in the Ashby/Clark material
    (for example see www.glosa.org/gid/simsyn.htm ).
- leads the user to prefereable synonyms and gives a basic vocabulary
    for beginners (Core, coglen.htm).

Actually there are included:
- "Glosa 1000 to English" list from the book "18 Steps to Fluency"
- "Glosa 6000"
- "English 5000 to Glosa 1000" list from the book "Central Glosa".
- the list from the book "Francais - Glosa 1000".

Unfortunately not included yet:
- the list from the book "Deutsch - Glosa 1000"
- the list from the book "Español - Glosa 1000"
- the "Central"-list, book "Central Glosa", p. 25-56 (very important)
- the vocabulary from the lessons and pictures of "18 Steps to
  Fluency ..."
- vocabulary from as many as we can PGN-articles.

Sad: before this work done (scanning the Ashby/Clark material), I do
not see reasonable space for creativity in creation of new words for a
Glosa dictionary.

But the good news: we do not yet have to found a
word-creation-committee right now with all its fights and troubles.



 >   P.S.  I hope that everyone is thinking about the article they are
 > going to write, in Glosa, to submit for the next Plu Glosa Nota.
 > Mine will be about the recent drought and bush-fires, here in
 > Australia.  ...

I am looking forward to reading it!  Hedo 2003 ko saluta ex Marcel.



---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: glosalist{at}lists{dot}zeta{dot}org{dot}au
Subject: Re: [glosalist] developing tutorial - pgn78
From: Robin Gaskell <rgaskell{at}zeta{dot}org{dot}au>
Date: Fri, 03 Jan 2003 02:22:04 +1100

At 03:39 PM 12/18/02 EST, you wrote:
>Here are extracts from PGN87 perhaps for a projected tutorial. It is
probably 
>more useful to become at ease with translating from Glosa to English or
other 
>tongue befare doing much into Glosa. We need pieces of Glosa that are 
>actually in use rather than purpose built examples and we need to get clear 
>the structures of the sentences. 
*  Very true: but I suspect that more needs to be writen in Glosa to give
us as wide a choice as possible.  Simpler practical sentences would be
better starting points, for learners, than this complicated on.

>   There has been a tendency in English and in 
>Glosa to shrink away from grammar. 
*   And this - for Glosa - requires a generally understood concept of how
syntax-based grammar works, in the setting of words that are not labelled
as distinct parts of speech.  What actual elements of grammar are valid for
Glosa?
My thought is that the Functional Grammar approach, created by MAK
Halliday, is probably the closest of the published theories.  However, I
still believe that, considering Funtional Grammar was invented primarily
for English, its concepts will need some tweaking for Glosa.

Earlier in tutors one was given long lists 
>and tables especially of irregularities. Here is the first sentence in this 
>PGN, my apologies to its author for not asking permission.
>  
*  Should not be necessary: once published in PGN, the utterance is in the
Public Domain.

>[alphabet and sounds can be inserted later]
>
*  Printed alphabet is easy, but the sound of the letters, and the
pronunciation of the words require much more technology, and can prove
difficult.  I still recall the reply from a Glosa contact in Brazil, to
whom I sent a cassette of spoken glosa.  "Thank you.  It looks very nice,
but I know no-one with a cassette player, so I can't hear it."

>'Tem pre oligo meno plu nova-papira-pe e komerci-pe pa dice de u ski de plu 
>lingua in Englanda.' 
>
> [EXTRA PHRASE(time)  while before few months  [Tem pre oligo meno] = a few 
>months ago    
>SUBJECT      some newspaper-people and commerce-people   [plu nova-papira-pe 
>e komerci-pe]
>VERB         did speak   [pa dice] 
>OBJECT       of the know   [de u ski]
>             of the languages   [de plu lingua]
>             in England  [in Englanda]
>
>introducing words:- 'plu'/some introduces the subject noun phrase
>'did' introduces the verb phrase
>'of the' introduces the object phrase
>'while before' introduces the extra phrase of time
>
>'people' are the two head words in the subject phrase
>'speak' is the head word in the verb phrase
>'know' is the head of the object
>'months' is the head of the extra phrase
>
>'newspaper'/'commerce' modify [ help/clarify/add to the meaning of] 'people'
>'of the languages' modifies 'know'
>'in England' modifies 'languages'
>EXTRA modifies the verb phrase
>'few' introduces months [a noun phrase inside an extra phrase]
>
*  All very true, but how many raw recruits will plough though all this -
or understand the elements, and their significance?
   I question the format of your method here.  I have always preferred the
line under line approach whereby the learner can see the related parts and
their explanations, directly under one another.

Saluta,

Robin


---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: glosalist{at}lists{dot}zeta{dot}org{dot}au
Subject: Re: [glosalist] poem for PGN
From: Sydpidd{at}aol{dot}com
Date: Thu, 2 Jan 2003 15:14:50 EST

U poesi/verba-pikturi
Supra Plu Nefo [28nord16uest]


Infra .... plu nefo     tenu ge-difusi rako-margina 
leuko
       
Infra  inter-nefo .... urba   ge-difusi rako-margina 
leuko rosa kloro 

Horizo .... leuko polio rako-margina     nefo dura

Pusi-supra   dista  .... polio akuto klari    plu 
monta-akro

Infra mu dista .... no vista 

Gran Canaria


Cirka .... plu pina dendro

Dia plu aku ....  plu nefo       epi plu aku .... 
plu guta

Supra  ....   alti-koni       ab coni .... plu  
gentili sedati klina     solo nudi aridi


Na sta epi cinera


Ex .... piro explode erupti vulkani fumi  
fo-termo liqi-petro

de longi tem pa


Na sta a pedi de El Teide     

sid

---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: glosalist{at}lists{dot}zeta{dot}org{dot}au
Subject: [glosalist] hedo neo anua
From: "Carmelo Mico" <ranibakt{at}ozu{dot}es>
Date: Sun, 05 Jan 2003 16:16:57 +0100

Karo Marcel
Mi cepti tu karo grama a mi pro neo anua e mi gratia tu 
pro id.
Tem mo meno mi pa es fo pato e mi ne pa pote vide tu grama 
e
ko-co mi ne pa pote grafo epi Glosa-list.
Mi pa debi resta in pato-do (pro pneumonia)e ko-co in mi 
domi
mi pa resta in kli panto-di sine kine te gene kura.
Mi mali-fortuna ne habe internet-nexu in mi domi e mi ne 
pa pote
nek grafo e nek lekto qod pa acide epi internet-eko-lo. 
Boni-fortuna mi ne pa habe problema ko mi ergo e ko-co 
nu-di mi 
habe mi ergo in ergo-do. Mi bali u-ci grama ko-co epi 
Glosa-list
te saluta panto glosa-pe e doni ad an mi maxi boni desira 
pro 
sani e paci neo anua.
Mi fu bali a tu kron id es posi, u traduce de gramatika de 
Glosa
in francais lingua, e mi fu dura u traduce de 
Bhagavad-Gita in 
Glosa e kron id est ge-face mi fu bali a tu.
Mi es fo kontenta de plu lexi de W. Ashby pro mi traduce 
de Bhagavad
Gita sed mali fortuna mi ne habe fe adresi te grafo ad fe,
e mi ne ski u-ci jurnali "plu glosa nota" te lekto qod fe 
pa grafo,
qe id es epi Internet-pagini? Qe tu ski u adresi e tu pote 
komunika
a mi?Alimode tu pote grafo a fe ke mi es fo kontenta de fe 
lexi pro me,
e ke mi fu dura panto-tem mi ergo pro Glosa.
Plu saluta tu panto-tem karo ami : Mico Carmelo Ranibakt. 
 
--------------------------------------------------
Ya tenemos Lotería de NAVIDAD, descúbrelo aquí: http://loteria.ozu.es 
--------------------------------------------------
Correo enviado desde http://www.ozu.es



---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: glosalist{at}lists{dot}zeta{dot}org{dot}au
Subject: Re: [glosalist] hedo neo anua
From: Sydpidd{at}aol{dot}com
Date: Mon, 6 Jan 2003 05:49:47 EST

Wendi Ashby
Glosa Education Organisation
P.O. 18
Richmond 
Surrey
TW9 2GE
England

sid

---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Subject: Re: [glosalist] hedo neo anua
From: "Marcel Springer" <marcel{at}mspringer{dot}de>
Date: Mon, 6 Jan 2003 14:35:01 +0100


Carmelo Mico grafo, 2003-01-05:
 > Mi es fo kontenta de plu lexi de W. Ashby pro mi traduce de Bhagavad
 > Gita sed mali fortuna mi ne habe fe adresi te grafo ad fe, e mi ne
 > ski u-ci jurnali "plu glosa nota" te lekto qod fe pa grafo, qe id
 > es epi Internet-pagini? Qe tu ski u adresi e tu pote komunika a mi?
 
Wendy ne habe inter-reti nexu.  Fe landa-adresa es:

   Wendy Ashby
   Glosa Education Organisation
   P. O. Box 18
   Richmond
   Surrey TW9 2GE
   England

U pusi (bi DIN-A3 papira) jurnali "Plu Glosa Nota" es solo ex papira.
Id ne habe inter-reti versio.


 > Mi pa debi resta in pato-do (pro pneumonia) e ko-co in mi domi
 > mi pa resta in kli panto-di sine kine te gene kura.

Mi hedo lekto ex tu, karo Ranibakt, sed mi habe tristi, tu pa es pato.
Tu e panto Glosa-pe habe sani in 2003!  Saluta ex Marcel.




---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: glosalist{at}lists{dot}zeta{dot}org{dot}au
Subject: Re: [glosalist] IAL collectors
From: Sydpidd{at}aol{dot}com
Date: Sun, 12 Jan 2003 10:32:48 EST

This web page might interest some of the IAL collectors amongst us.
something I'm putting together to be as simple and none european etc as I 
can. Later, I shall see what has already been done on similar lines.
I suspect there is need for a few IALs, if they are worth their salt, several 
could be learned without too much trouble.
sid



http://hometown.aol.co.uk/sydpidd/index.html

---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: glosalist{at}lists{dot}zeta{dot}org{dot}au
Subject: Re: [glosalist] IAL collectors
From: Xipirho <xipirho{at}runbox{dot}com>
Date: Sun, 12 Jan 2003 17:03:58 +0000

--Apple-Mail-10--340670715
Content-Transfer-Encoding: 7bit
Content-Type: text/plain;
	charset=US-ASCII;
	format=flowed

looks good, but there still seem to be some hints of europeanness, not 
that i personally mind that at all. the words seem easier to remember 
than lojban. do you think you could put some of what you wrote (e.g. 
word order) in layman's terms for me? - i'm not an IAL expert. is <c> 
realy [c] in this systme - seems a bit of an uncommon sound to use 
doesnt it (not that i dont like the sound - its very easy to say) and 
couldnt it change to [tS] in speach rather too easily?

On Sunday, January 12, 2003, at 03:32  pm, Sydpidd{at}aol{dot}com wrote:

> This web page might interest some of the IAL collectors amongst us.
> something I'm putting together to be as simple and none european etc 
> as I
> can. Later, I shall see what has already been done on similar lines.
> I suspect there is need for a few IALs, if they are worth their salt, 
> several
> could be learned without too much trouble.
> sid
>
>
>
> http://hometown.aol.co.uk/sydpidd/index.html
>
> ---------------------------------------------------------------------
> To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
> For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
>
>
>
Liv long and prospx, Khjpjrho (Xipirho)/Rxwlj (Roly).

--Apple-Mail-10--340670715
Content-Transfer-Encoding: 7bit
Content-Type: text/enriched;
	charset=US-ASCII

looks good, but there still seem to be some hints of europeanness, not
that i personally mind that at all. the words seem easier to remember
than lojban. do you think you could put some of what you wrote (e.g.
word order) in layman's terms for me? - i'm not an IAL expert. is <<c>
realy [c] in this systme - seems a bit of an uncommon sound to use
doesnt it (not that i dont like the sound - its very easy to say) and
couldnt it change to [tS] in speach rather too easily?


On Sunday, January 12, 2003, at 03:32  pm, Sydpidd{at}aol{dot}com wrote:


<excerpt>This web page might interest some of the IAL collectors
amongst us.

something I'm putting together to be as simple and none european etc
as I 

can. Later, I shall see what has already been done on similar lines.

I suspect there is need for a few IALs, if they are worth their salt,
several 

could be learned without too much trouble.

sid




http://hometown.aol.co.uk/sydpidd/index.html


---------------------------------------------------------------------

To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au

For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au




</excerpt><fontfamily><param>Helvetica</param><smaller>Liv long and
prospx, Khjpjrho (Xipirho)/Rxwlj (Roly).</smaller></fontfamily>

--Apple-Mail-10--340670715
Content-Type: text/plain; charset=

---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
--Apple-Mail-10--340670715--
................................................................

// XXX REMARK -- New message:
................................................................
To: glosalist{at}lists{dot}zeta{dot}org{dot}au
Subject: Re: [glosalist] IAL collectors
From: Sydpidd{at}aol{dot}com
Date: Mon, 13 Jan 2003 11:09:17 EST

--part1_14.72c1e7e.2b543ead_boundary
Content-Type: text/plain; charset="US-ASCII"
Content-Transfer-Encoding: 7bit

glad to have your reply. hope this helps - will put more on the web page to 
build things up a bit more and explain better
sid

LAYMAN'S TERMS
This applies to Glosa and Glosalist also. I used to know a fair amount of 
linguist jargon but some that gets bandied about on the list has me 
flummoxed.
In Glosa, English and many other languages the verb/doing word/etc comes in 
the middle[ish] of the sentence, the subject before it and the object after:- 
subject[fox] verb[jumps] 'object'[dog]. In Hindi the verb comes last:- fox 
dog jumps. I found that subject and object gets mixed together in my mind - I 
prefer SVO. 
In 'the quick brown fox', the phrase is introduced by 'the' which tells us 
that we have a noun phrase [subject/object]. The most important word is 'fox' 
so I'm calling it 'head word'. 'quick' and 'brown' add more meaning/precision 
to the head word, they modify the meaning.They are modifiers.
In Eng or Glosa, I first meet the intro word [very useful] but I now have to 
read and memorise the next 4 words before I can find the head w. In Eng word 
4 [jumps] is clearly a verb so 'fox' is the head. If I am new to E or G, that 
is not too easy.
In my experiment, I have intro [the] head [fox] and then the less important 
stuff [quick, brown]
fox jump dog
with the intro words
the fox do jump the dog
THE FOX quick brown DO JUMP [over] THE DOG lazy
? shall consider 'over' is a modifier of 'jump'
If someone is new, he/she can ignore the less important stuff until he/she 
gets the basic meaning

'c'
I have suggested that the pronunciation is the same as that in IPA - more 
perhaps later.
b d f  k l m n p s t v z sound much as in English.
c sounds much like 'ch' in 'church', j is like 'y'in 'yes', r is 
rolled/trilled, g is always like 'get'.

In a message dated 2003-01-12 05:05:20 GMT Standard Time, xipirho{at}runbox{dot}com 
writes:


> 
> looks good, but there still seem to be some hints of europeanness, not 
> that i personally mind that at all. the words seem easier to remember 
> than lojban. do you think you could put some of what you wrote (e.g. 
> word order) in layman's terms for me? - i'm not an IAL expert. is <c> 
> realy [c] in this systme - seems a bit of an uncommon sound to use 
> doesnt it (not that i dont like the sound - its very easy to say) and 
> couldnt it change to [tS] in speach rather too easily?
> 


--part1_14.72c1e7e.2b543ead_boundary
Content-Type: text/html; charset="US-ASCII"
Content-Transfer-Encoding: 7bit

<HTML><FONT FACE=arial,helvetica><FONT  SIZE=2>glad to have your reply. hope this helps - will put more on the web page to build things up a bit more and explain better<BR>
sid<BR>
<BR>
LAYMAN'S TERMS<BR>
This applies to Glosa and Glosalist also. I used to know a fair amount of linguist jargon but some that gets bandied about on the list has me flummoxed.<BR>
In Glosa, English and many other languages the verb/doing word/etc comes in the middle[ish] of the sentence, the subject before it and the object after:- subject[fox] verb[jumps] 'object'[dog]. In Hindi the verb comes last:- fox dog jumps. I found that subject and object gets mixed together in my mind - I prefer SVO. <BR>
In 'the quick brown fox', the phrase is introduced by 'the' which tells us that we have a noun phrase [subject/object]. The most important word is 'fox' so I'm calling it 'head word'. 'quick' and 'brown' add more meaning/precision to the head word, they modify the meaning.They are modifiers.<BR>
In Eng or Glosa, I first meet the intro word [very useful] but I now have to read and memorise the next 4 words before I can find the head w. In Eng word 4 [jumps] is clearly a verb so 'fox' is the head. If I am new to E or G, that is not too easy.<BR>
In my experiment, I have intro [the] head [fox] and then the less important stuff [quick, brown]<BR>
fox jump dog<BR>
with the intro words<BR>
the fox do jump the dog<BR>
THE FOX quick brown DO JUMP [over] THE DOG lazy<BR>
? shall consider 'over' is a modifier of 'jump'<BR>
If someone is new, he/she can ignore the less important stuff until he/she gets the basic meaning<BR>
<BR>
'c'<BR>
I have suggested that the pronunciation is the same as that in IPA - more perhaps later.<BR>
b d f&nbsp; k l m n p s t v z sound much as in English.<BR>
c sounds much like 'ch' in 'church', j is like 'y'in 'yes', r is rolled/trilled, g is always like 'get'.<BR>
<BR>
In a message dated 2003-01-12 05:05:20 GMT Standard Time, xipirho{at}runbox{dot}com writes:<BR>
<BR>
<BR>
<BLOCKQUOTE TYPE=CITE style="BORDER-LEFT: #0000ff 2px solid; MARGIN-LEFT: 5px; MARGIN-RIGHT: 0px; PADDING-LEFT: 5px"><BR>
looks good, but there still seem to be some hints of europeanness, not <BR>
that i personally mind that at all. the words seem easier to remember <BR>
than lojban. do you think you could put some of what you wrote (e.g. <BR>
word order) in layman's terms for me? - i'm not an IAL expert. is &lt;c&gt; <BR>
realy [c] in this systme - seems a bit of an uncommon sound to use <BR>
doesnt it (not that i dont like the sound - its very easy to say) and <BR>
couldnt it change to [tS] in speach rather too easily?<BR>
</BLOCKQUOTE><BR>
<BR>
</FONT></HTML>

--part1_14.72c1e7e.2b543ead_boundary
Content-Type: text/plain; charset=

---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
--part1_14.72c1e7e.2b543ead_boundary--
................................................................

// XXX REMARK -- New message:
................................................................
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Subject: [glosalist] =?iso-8859-1?Q?Espa=F1ol-Glosa?=
From: "Marcel Springer" <marcel{at}mspringer{dot}de>
Date: Fri, 17 Jan 2003 07:50:10 +0100

The word-list from the book "Español - Glosa 1000" by Richard Burrows,
Wendy Ashby and Ronald Clark, 1992, is now online available:

   http://www.glosa.org/gid/esgl1k.htm .

Many thanks to Wendy Ashby.

A computer-reversed version Glosa-Spanish (not in the book) is:

  http://www.glosa.org/gid/gl1kes.htm .

Like the French list before, this word list needs some (months) work
yet.  There seem to be again a lot of differences and contradictions
to the other Glosa word lists (and so to the GID).

Marcel



---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: glosalist{at}lists{dot}zeta{dot}org{dot}au
Subject: Re: [glosalist] 31ndeveloping tutorial - pgn78
From: Sydpidd{at}aol{dot}com
Date: Tue, 21 Jan 2003 13:59:04 EST

adjustments to my tutor:-


'Mu pa veni a mi civita in Boreo Dakota'

'mu'     'they'    Subject

'pa'     'did'     verb phrase, start of phrase 
'veni'   'come'       * main word of phrase

'a'      'to'      Object noun phrase + preposition
'mi'     'my'           helps main word
'civita' 'city'       * main word
'in'     'in'           helps 'dakota'
'boreo'  'north'          helps next word
'Dakota' 'Dakota'     helps main word

'pa' introduces the verb phrase and signifies the past tense

The English is next to the Glosa, in vertical 
columns rather than horizontal ones, the 
structure in the next one. The reader can 
ignore the latter, skim through it or pore 
over it as wished. I rather like this 
approach myself and would find it helpful 
in learning Spanish for instance. 

---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: glosalist{at}lists{dot}zeta{dot}org{dot}au
Subject: Re: [glosalist] 31p IAL collectors
From: Sydpidd{at}aol{dot}com
Date: Wed, 22 Jan 2003 09:49:00 EST

something for collectors:-
'Mu pa veni a mi civita in Boreo Dakota'

lu        they    subject
va        did     intro verb phrase, past
gidibi    come     head verb phrase 
fa        to      object ......
na        the     intro noun phrase 
dukifu    city     head noun phrase 
de        of
ma        me      helps head NP
je        and
da        in
dakota    Dakota  also helps NP
gecelu    north    helps preceding word 

= lu va gidibi  fa na dukifu de ma  je da dakota gecelu -


stress on penultimate vowel, extra 
stress on 'di' in gibidi, 
greatest stress on  'ki' in dukifu

[come  295/2/2  gidibi]
[city  192/0/19 dukifu]
[north 281/0/39 gecelu]


---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: glosalist{at}lists{dot}zeta{dot}org{dot}au
Subject: [glosalist] NEW
From: Matthias Bigalke <bigalke{at}jendata{dot}de>
Date: Wed, 19 Feb 2003 21:46:03 +0100

Ave!
Mi nima es Matthias Bigalke.
Mi es neo.
Ed es ci no-soni.
Qe lista ge-frakti?

plu ami saluta,

Matthias

--
Hello,
My name ist Matthias Bigalke.
It is so calmly here.
Or is broken the list ?

Yours sincerely
Matthias

----
mb{at}jendata{dot}de




---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: glosalist{at}lists{dot}zeta{dot}org{dot}au, bigalke{at}jendata{dot}de
Subject: Re: [glosalist] NEW
From: Nicholas Hempshall <nick_hempshall{at}yahoo{dot}co{dot}uk>
Date: Wed, 19 Feb 2003 13:09:12 -0800 (PST)

Karo Matthias,

Bene-veni a glosa-lista!

Ja. Na taci nu-tem. 

Posi si tu fu posta plu qestio alo plu komenta; u
lista fu ma aktivi.

Poli ami saluta ex
Nick


__________________________________________________
Do you Yahoo!?
Yahoo! Shopping - Send Flowers for Valentine's Day
http://shopping.yahoo.com

---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>, <bigalke{at}jendata{dot}de>
Subject: Re: [glosalist] NEW
From: "Jay Bowks" <jjbowks{at}adam{dot}cheshire{dot}net>
Date: Wed, 19 Feb 2003 21:01:24 -0500

Saluta Matthias,
Bene-veni a lista de glosa.
Qo tu dice es veri. Qanto
no-soni, sed lista no es frakti.
Na es aktivi kon (sin) poli ra 
pro face. 

Komo tu esce interese in
Glosa? 

Plu ami-saluta,
Jay B.

----- Original Message ----- 
From: "Matthias Bigalke" <bigalke{at}jendata{dot}de>
> Ave!
> Mi nima es Matthias Bigalke.
> Mi es neo.
> Ed es ci no-soni.
> Qe lista ge-frakti?
> plu ami saluta,
> Matthias





---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Subject: [glosalist] Translation
From: "Anthony Thornton" <kewl4u{at}btinternet{dot}com>
Date: Fri, 28 Feb 2003 15:39:35 -0000

------=_NextPart_000_001D_01C2DF3F.987D08E0
Content-Type: text/plain;
	charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

Hello everyone,

I'm systems administrator for an International Penpals web site (well, 3 =
sites really) and just started learning Glosa.

My problem is that I would like to include a Glosa forum (discussion =
board) in our new bulletin board on our web site but I cannot work out =
the Glosa for "Glosa Forum" or "Glosa Message Board". Can anyone help?

The English description, "Messages in Glosa" probably translates into =
"Info in Glosa" but that translates back to English as "Information in =
Glosa". Again can anyone help with this one.

Anyway, I've ordered the book from amazon.co.uk and looking forward to =
learning the language.

Thanks,
Anthony,
http://www.andys-penpals.com/
------=_NextPart_000_001D_01C2DF3F.987D08E0
Content-Type: text/html;
	charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML><HEAD>
<META http-equiv=3DContent-Type content=3D"text/html; =
charset=3Diso-8859-1">
<META content=3D"MSHTML 6.00.2800.1141" name=3DGENERATOR>
<STYLE></STYLE>
</HEAD>
<BODY bgColor=3D#ffffff>
<DIV><FONT face=3DArial size=3D2>Hello everyone,</FONT></DIV>
<DIV><FONT face=3DArial size=3D2></FONT>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>I'm systems administrator for an =
International=20
Penpals web site (well, 3 sites really) and just started learning=20
Glosa.</FONT></DIV>
<DIV><FONT face=3DArial size=3D2></FONT>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>My problem is that I would like to =
include a Glosa=20
forum (discussion board)&nbsp;in our new&nbsp;bulletin board on our web=20
site&nbsp;but I cannot work out the Glosa for "Glosa Forum" or "Glosa =
Message=20
Board". Can anyone help?</FONT></DIV>
<DIV><FONT face=3DArial size=3D2></FONT>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>The English description, "Messages in=20
Glosa"&nbsp;probably translates into "Info in Glosa" but that translates =
back to=20
English&nbsp;as "Information in Glosa". Again can anyone help with this=20
one.</FONT></DIV>
<DIV><FONT face=3DArial size=3D2></FONT>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>Anyway, I've ordered the book from =
amazon.co.uk and=20
looking forward to learning the language.</FONT></DIV>
<DIV><FONT face=3DArial size=3D2></FONT>&nbsp;</DIV>
<DIV><FONT face=3DArial size=3D2>Thanks,</FONT></DIV>
<DIV><FONT face=3DArial size=3D2>Anthony,</FONT></DIV>
<DIV><FONT face=3DArial=20
size=3D2>http://www.andys-penpals.com/</FONT></DIV></BODY></HTML>


------=_NextPart_000_001D_01C2DF3F.987D08E0
Content-Type: text/plain; charset=

---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
------=_NextPart_000_001D_01C2DF3F.987D08E0--
................................................................

// XXX REMARK -- New message:
................................................................
To: glosalist{at}lists{dot}zeta{dot}org{dot}au
Subject: Re: [glosalist] Translation
From: Sydpidd{at}aol{dot}com
Date: Fri, 28 Feb 2003 14:02:29 EST

Glosa Diskursi Grega - alo.... Glosa Diskursi Grupo       ?
sid

---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Subject: [glosalist] www.andys-penpals.com
From: "Marcel Springer" <marcel{at}mspringer{dot}de>
Date: Sat, 1 Mar 2003 09:28:15 +0100

Karo Anthony, bene-veni a Glosalist!  Gratia de tu interese de Glosa!

Tu grafo, 2003-02-18:
 > I'm systems administrator for an International Penpals web site
 > (well, 3 sites really) and just started learning Glosa.
 >
 > My problem is that I would like to include a Glosa forum
 > (discussion board) in our new bulletin board on our web site but I
 > cannot work out the Glosa for "Glosa Forum" or "Glosa Message
 > Board". Can anyone help?
 >
 > ...
 >
 > Anyway, I've ordered the book from amazon.co.uk and looking forward
 > to learning the language.

I am sorry for this warning: the Glosa books may disappoint you.

I just wanted to answer your letter and make a translation suggestion
for you.  But before sending it, I saw, you have been quicker:

I received a mail from you, 2003-03-01:
 > Andy's Penpals International has linked to your web site located at
 > http://www.glosa.org/
 > ...
 > Reciprocal linking is not required. However, should you wish to do
 > so, you may find a link to our forums which includes a Glosa
 > Discussion Group forum more appropriate for your web site links
 > section:
 > http://www.andys-penpals.com/cgi-bin/cutecast/cutecast.pl
 > Please note that the forum is new today and may take some time to
 > get started as we introduce our site visitors and members to Glosa.
 > Our eventual aim is to learn Glosa sufficiently for us to write
 > language files for a Glosa language option on all sites and the
 > forums. This may take some time.

Thank you very much!  I wish you good luck for your business.  I just
registered.

Unfortunately the user community of Glosa is very small.  It would not
make much sense to devide the few communication in/about Glosa to two
discussion forums yet, I fear.  On the other hand, glosalist{at}zeta{dot}org
is not very comfortable and often spammed.

Please let me quote the text from your website and send it to
Glosalist.  It is certainly very interesting for the other
Glosa-people.

Website www.andys-penpals.com :
 > Andy's Penpals has been investigating international, constructed
 > languages for a while now and has made the final choice.
 >
 > Glosa (pronounced glawsa) looks to be easier to learn than other
 > constructed languages like Esperanto.
 >
 > First up is a Glosa forum on these boards now.
 >
 > The books have been ordered and everyone thinks we'll be speaking
 > Glosa in no time. The eventual aim is to have Glosa as a language
 > option on these boards and also on the two penpals web sites.
 >
 > Anyway, anyone who is interested in Glosa may like to take a look
 > at http://www.glosa.org/
 >
 > Carolyn

Again many thanks and good luck - Marcel.




---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Subject: Re: [glosalist] www.andys-penpals.com
From: "Anthony Thornton" <kewl4u{at}btinternet{dot}com>
Date: Sat, 1 Mar 2003 10:58:37 -0000

Hi again,

It has probably been realized by many but maybe someone has to say it and
that someone is probably me: Perhaps if organisations like Andy's Penpals
become interested in Glosa, then perhaps the worldwide Glosa community would
not be so small as I think it probably is at present. Andy's Penpals is not
exactly small with over 16,000 members, though not all active, and over
14,000 unique visitors to all sites per month, but then not exactly big by
Internet standards. But our problem is that our Users tend to be very
conservative (with a small c) as anyone can see from the small numbers of
members who are joining the Forums. But a few signed up followed by a few
more and so on, so perhaps the few will turn into the many in time. Maybe
it'll be this way with Glosa.

Anyway, getting the books is not going well, so I've written a letter to the
Organisation in Surrey for a list of books and hopefully I'll receive a
reply soon. Marcel's web site is invaluable and I congratulate him on a job
well done. I had no hesitation in linking to it. Why Glosa? Well, it's
something new and perhaps we and our users need something new to revive us.
And, of course, an international language is a very attractive proposition
for any international organisation. We'll stick with it until hell freezes
over and the results will probably be what the results will be.

I'll end by sincerely apologising for posting in English and maybe I'll be
able to post in Glosa soon. Maybe someone can translate this post into Glosa
for me?

With very best wishes,
Anthony

----- Original Message -----
From: "Marcel Springer" <marcel{at}mspringer{dot}de>
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Sent: Saturday, March 01, 2003 8:28 AM
Subject: [glosalist] www.andys-penpals.com


> Karo Anthony, bene-veni a Glosalist!  Gratia de tu interese de Glosa!
>
> Tu grafo, 2003-02-18:
>  > I'm systems administrator for an International Penpals web site
>  > (well, 3 sites really) and just started learning Glosa.
>  >
>  > My problem is that I would like to include a Glosa forum
>  > (discussion board) in our new bulletin board on our web site but I
>  > cannot work out the Glosa for "Glosa Forum" or "Glosa Message
>  > Board". Can anyone help?
>  >
>  > ...
>  >
>  > Anyway, I've ordered the book from amazon.co.uk and looking forward
>  > to learning the language.
>
> I am sorry for this warning: the Glosa books may disappoint you.
>
> I just wanted to answer your letter and make a translation suggestion
> for you.  But before sending it, I saw, you have been quicker:
>
> I received a mail from you, 2003-03-01:
>  > Andy's Penpals International has linked to your web site located at
>  > http://www.glosa.org/
>  > ...
>  > Reciprocal linking is not required. However, should you wish to do
>  > so, you may find a link to our forums which includes a Glosa
>  > Discussion Group forum more appropriate for your web site links
>  > section:
>  > http://www.andys-penpals.com/cgi-bin/cutecast/cutecast.pl
>  > Please note that the forum is new today and may take some time to
>  > get started as we introduce our site visitors and members to Glosa.
>  > Our eventual aim is to learn Glosa sufficiently for us to write
>  > language files for a Glosa language option on all sites and the
>  > forums. This may take some time.
>
> Thank you very much!  I wish you good luck for your business.  I just
> registered.
>
> Unfortunately the user community of Glosa is very small.  It would not
> make much sense to devide the few communication in/about Glosa to two
> discussion forums yet, I fear.  On the other hand, glosalist{at}zeta{dot}org
> is not very comfortable and often spammed.
>
> Please let me quote the text from your website and send it to
> Glosalist.  It is certainly very interesting for the other
> Glosa-people.
>
> Website www.andys-penpals.com :
>  > Andy's Penpals has been investigating international, constructed
>  > languages for a while now and has made the final choice.
>  >
>  > Glosa (pronounced glawsa) looks to be easier to learn than other
>  > constructed languages like Esperanto.
>  >
>  > First up is a Glosa forum on these boards now.
>  >
>  > The books have been ordered and everyone thinks we'll be speaking
>  > Glosa in no time. The eventual aim is to have Glosa as a language
>  > option on these boards and also on the two penpals web sites.
>  >
>  > Anyway, anyone who is interested in Glosa may like to take a look
>  > at http://www.glosa.org/
>  >
>  > Carolyn
>
> Again many thanks and good luck - Marcel.
>
>
>
>
> ---------------------------------------------------------------------
> To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
> For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
>
>



---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: glosalist{at}lists{dot}zeta{dot}org{dot}au
Subject: Re: [glosalist] fox and dogs - head first
From: Sydpidd{at}aol{dot}com
Date: Sun, 2 Mar 2003 11:19:32 EST

Beause of memory problems, I have difficulty with languages new [and 
sometimes old] to me. so.....

"The quick":- here we have an NP introducing word and what might be the 
phrase's head word, the noun. i.e. ' The quick of my thumb hurts' ......
"The quick brown":- no, 'quick modifies the head noun 'brown'  highly 
unlikely! ......
"The quick brown fox" 'fox' is the head 'q...', 'b...', are modifiers.
"The quick brown fox jumps":- we have a verb. 
"The quick brown fox jumps over the lazy dog":- we now have a meaningful 
sentence.
However, those of you with better eyesight than mine will have noticed the 
lack of a full stop after dog. To finish the sentence, we have, 
"   ...................... dog are very high.   ". The subject head noun is 
now 'jumps'. 
I've had to wade through the sentence forming ideas of the structure, 
cancelling them, reforming them and so on.

"The jumps, fox quick and brown, over the dog, lazy do have the height, 
great"  intro word, head, modifiers 
"The fox quick and brown does jump over the dog lazy"
I know by the second word in the phrase which is the head/important and can 
pay less attention to the modifiers.
To rob glosa,
"U vulpe tako e bruno nu salta su u kanis indole.
To mathematically maul the Roget thesaurus,
'na jikeju gasi je kiga  vi goki  su nu jiki pavufo -'

Are there any conlangs that use intro + head + modifiers as a construction?

---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: glosalist{at}lists{dot}zeta{dot}org{dot}au
Subject: Re: [glosalist] fox and dogs - head first
From: Andrew Dabrowski <dabrowsa{at}indiana{dot}edu>
Date: Mon, 03 Mar 2003 10:56:33 -0500

I think you've identified the main problem with Glosa in its present form: 
sentence parsing.  Hogben was quite clear originally that syntax is one of the 
main stumbling blocks in learning a new language, and especially in a language 
like Glosa, in which a single word can be used as different parts of speech, a 
rigid syntax was necessary.  Hence his use of verboids.  But verboids have 
largely gone by the wayside, and now Glosa can extremely difficult for beginners 
like me to parse.

Perhaps some system of marking words for their roles in the sentence would help, 
for example the German convention of capitalizing nouns.


Sydpidd{at}aol{dot}com wrote:
> Beause of memory problems, I have difficulty with languages new [and 
> sometimes old] to me. so.....
> 
> "The quick":- here we have an NP introducing word and what might be the 
> phrase's head word, the noun. i.e. ' The quick of my thumb hurts' ......
> "The quick brown":- no, 'quick modifies the head noun 'brown'  highly 
> unlikely! ......
> "The quick brown fox" 'fox' is the head 'q...', 'b...', are modifiers.
> "The quick brown fox jumps":- we have a verb. 
> "The quick brown fox jumps over the lazy dog":- we now have a meaningful 
> sentence.
> However, those of you with better eyesight than mine will have noticed the 
> lack of a full stop after dog. To finish the sentence, we have, 
> "   ...................... dog are very high.   ". The subject head noun is 
> now 'jumps'. 
> I've had to wade through the sentence forming ideas of the structure, 
> cancelling them, reforming them and so on.
> 
> "The jumps, fox quick and brown, over the dog, lazy do have the height, 
> great"  intro word, head, modifiers 
> "The fox quick and brown does jump over the dog lazy"
> I know by the second word in the phrase which is the head/important and can 
> pay less attention to the modifiers.
> To rob glosa,
> "U vulpe tako e bruno nu salta su u kanis indole.
> To mathematically maul the Roget thesaurus,
> 'na jikeju gasi je kiga  vi goki  su nu jiki pavufo -'
> 
> Are there any conlangs that use intro + head + modifiers as a construction?
> 
> ---------------------------------------------------------------------
> To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
> For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
> 
> 


-- 
Andrew Dabrowski    |...it is a ghost's right / his element is so fine / being
Bloomington IN USA  |sharpened by his death / to drink from the wine breath /
dabrowsa{at}indiana{dot}edu|while our gross palates drink from the whole wine. -Yeats


---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Subject: [glosalist] "Happy Lady Day" has an VIRUS!!!
From: Charles{at}Catty{dot}Com
Date: Sun, 23 Mar 2003 12:52:22 -0800

Marcel wrote:

> Attention! VIRUS!!

Linux is not vulnerable to such pranks. Supporting
Microsoft is like supporting terrorist organizations.

Anyway, this list and Glosa are moribund. And we
can't blame Esperanto or other outside forces.


---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Subject: Re: [glosalist] "Happy Lady Day" has an VIRUS!!!
From: "Anthony Thornton" <kewl4u{at}btinternet{dot}com>
Date: Sun, 23 Mar 2003 22:45:53 -0000

Hey,

Windows is only vulnerable to viruses if you don't have an anti-virus
program.

Anyway, the virus was probably not sent from the email it says it's from.
What the Klez virus and its variants does is to select an email address from
the infected computer's files and uses that as the from address.

But what it does mean is that someone who is on the glosalist list is
infected. Symantec has a free on-line virus-scanner at
http://security.symantec.com/ using Norton anti-virus. Also the Downloads
link has free downloads of removal tools. Go use it if you think your
computer is infected. (if you don't have an anti-virus program, it probably
is).

Best wishes,
Anthony

----- Original Message -----
From: <Charles{at}Catty{dot}Com>
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Sent: Sunday, March 23, 2003 8:52 PM
Subject: [glosalist] "Happy Lady Day" has an VIRUS!!!


> Marcel wrote:
>
> > Attention! VIRUS!!
>
> Linux is not vulnerable to such pranks. Supporting
> Microsoft is like supporting terrorist organizations.
>
> Anyway, this list and Glosa are moribund. And we
> can't blame Esperanto or other outside forces.
>
>
> ---------------------------------------------------------------------
> To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
> For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
>
>



---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Subject: [glosalist] mail "Windows" is VIRUS-infected
From: "Marcel Springer" <marcel{at}mspringer{dot}de>
Date: Mon, 24 Mar 2003 07:48:41 +0100

Attention! VIRUS!!!

Another attack ... 

Please do not open the files, which has been attached to the
mail "Windows" by "maconly" (today, 2003-03-24). 

It is infected with the virus W32/Klez.H{at}mm{dot}

(I did a virus check, and it does not seem to be me.) 

Saluta,

Marcel




---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Subject: [glosalist] Karo Charles!
From: "Marcel Springer" <marcel{at}mspringer{dot}de>
Date: Mon, 24 Mar 2003 08:09:35 +0100

Charles grafo, 2003-03-23: 
 > Anyway, this list and Glosa are moribund. 

No, mi ne akorda.  Saluta ex Marcel. 


---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Subject: Re: [glosalist] mail "Windows" is VIRUS-infected
From: "Anthony Thornton" <kewl4u{at}btinternet{dot}com>
Date: Mon, 24 Mar 2003 07:14:18 -0000

Not me either. I have Norton anti-virus, my ISP has the Brightmail virus
scanner and all my outgoing email is virus-scanned.

BTW I got the books and am now going to learn Glosa. 1,000 words shouldn't
be too difficult. What I'm wondering is what is "pen pal" in Glosa? Pen pal
translates as stilo ami. But probably the European version of pen pal, mail
friend, translated to posta ami is more accurate.

But what's email? eposta?

Best wishes,
Anthony

----- Original Message -----
From: "Marcel Springer" <marcel{at}mspringer{dot}de>
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Sent: Monday, March 24, 2003 6:48 AM
Subject: [glosalist] mail "Windows" is VIRUS-infected


> Attention! VIRUS!!!
>
> Another attack ...
>
> Please do not open the files, which has been attached to the
> mail "Windows" by "maconly" (today, 2003-03-24).
>
> It is infected with the virus W32/Klez.H{at}mm{dot}
>
> (I did a virus check, and it does not seem to be me.)
>
> Saluta,
>
> Marcel
>
>
>
>
> ---------------------------------------------------------------------
> To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
> For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
>
>



---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: glosalist{at}lists{dot}zeta{dot}org{dot}au
Subject: [glosalist] Virus (e saluta)
From: Gary R Miller <justi.miller{at}juno{dot}com>
Date: Mon, 24 Mar 2003 22:56:59 -0600

Proto: Saluta, panto Glosa-pe!  Mi nima es Gary Miller.  Mi pa lekto
_Glosalist_ mega-tem e nu-pa gene subskribe de id.

Gratia, Marcel.  Mi pa gene panto-ci e-grama, anti-co mu es vaku e habe
zero nexu-ra.  (Mi habe anti-virus programa.)

Kon ami saluta,
 _  _
  /.   Gary
#/\#
 ###

________________________________________________________________
Sign Up for Juno Platinum Internet Access Today
Only $9.95 per month!
Visit www.juno.com

---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Subject: [glosalist] Re: glosalist Digest 25 Mar 2003 02:52:20 -0000 Issue 338
From: <bertrand{at}fintrans{dot}ch>
Date: Tue, 25 Mar 2003 09:50:24 +0100

unsubscribe
Bertrand Finckler
fon:   +41(0)43 317 94 90
mob: +41(0)79 312 77 32

----- Original Message ----- 
From: <glosalist-digest-help{at}lists{dot}zeta{dot}org{dot}au>
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Sent: Tuesday, March 25, 2003 3:52 AM
Subject: glosalist Digest 25 Mar 2003 02:52:20 -0000 Issue 338





---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Subject: Re: [glosalist] Virus (e saluta)
From: <bertrand{at}fintrans{dot}ch>
Date: Tue, 25 Mar 2003 09:52:16 +0100

pls. unsubscribe
Bertrand Finckler
fon:   +41(0)43 317 94 90
mob: +41(0)79 312 77 32

----- Original Message ----- 
From: "Gary R Miller" <justi.miller{at}juno{dot}com>
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Sent: Tuesday, March 25, 2003 5:56 AM
Subject: [glosalist] Virus (e saluta)


> Proto: Saluta, panto Glosa-pe!  Mi nima es Gary Miller.  Mi pa lekto
> _Glosalist_ mega-tem e nu-pa gene subskribe de id.
> 
> Gratia, Marcel.  Mi pa gene panto-ci e-grama, anti-co mu es vaku e habe
> zero nexu-ra.  (Mi habe anti-virus programa.)
> 
> Kon ami saluta,
>  _  _
>   /.   Gary
> #/\#
>  ###
> 
> ________________________________________________________________
> Sign Up for Juno Platinum Internet Access Today
> Only $9.95 per month!
> Visit www.juno.com
> 
> ---------------------------------------------------------------------
> To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
> For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
> 
> 
> 



---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Subject: [glosalist]  Keep me informed on any info favorable to Glosa language.  rqtn{at}esper{dot}com
From: "Richard Queener" <rqtn{at}esper{dot}com>
Date: Wed, 26 Mar 2003 17:06:44 -0800

------=_NextPart_000_012A_01C2F3BA.13CD8D60
Content-Type: text/plain;
	charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable


  ----- Original Message -----=20
  From: jmaffei=20
  To: glosalist{at}lists{dot}zeta{dot}org{dot}au=20
  Sent: Tuesday, March 25, 2003 3:09 PM
  Subject: [glosalist] A very new website


  This is a very new website
  I wish you would like it.=20

------=_NextPart_000_012A_01C2F3BA.13CD8D60
Content-Type: text/html;
	charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML><HEAD>
<META content=3D"text/html; charset=3Diso-8859-1" =
http-equiv=3DContent-Type>
<META content=3D"MSHTML 5.00.2314.1000" name=3DGENERATOR>
<STYLE></STYLE>
</HEAD>
<BODY bgColor=3D#ffffff>
<DIV>&nbsp;</DIV>
<BLOCKQUOTE=20
style=3D"BORDER-LEFT: #000000 2px solid; MARGIN-LEFT: 5px; MARGIN-RIGHT: =
0px; PADDING-LEFT: 5px; PADDING-RIGHT: 0px">
  <DIV style=3D"FONT: 10pt arial">----- Original Message ----- </DIV>
  <DIV=20
  style=3D"BACKGROUND: #e4e4e4; FONT: 10pt arial; font-color: =
black"><B>From:</B>=20
  <A href=3D"mailto:jmaffei{at}comcast{dot}net" =
title=3Djmaffei{at}comcast{dot}net>jmaffei</A>=20
  </DIV>
  <DIV style=3D"FONT: 10pt arial"><B>To:</B> <A=20
  href=3D"mailto:glosalist{at}lists{dot}zeta{dot}org{dot}au"=20
  title=3Dglosalist{at}lists{dot}zeta{dot}org{dot}au>glosalist{at}lists{dot}zeta{dot}org{dot}au</A> =
</DIV>
  <DIV style=3D"FONT: 10pt arial"><B>Sent:</B> Tuesday, March 25, 2003 =
3:09=20
  PM</DIV>
  <DIV style=3D"FONT: 10pt arial"><B>Subject:</B> [glosalist] A very new =

  website</DIV>
  <DIV><BR></DIV><FONT size=3D+0>This is a very new website<BR>I wish =
you would=20
  like it.</FONT> </BLOCKQUOTE></BODY></HTML>


------=_NextPart_000_012A_01C2F3BA.13CD8D60
Content-Type: text/plain; charset=

---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
------=_NextPart_000_012A_01C2F3BA.13CD8D60--
................................................................

// XXX REMARK -- New message:
................................................................
To: glosalist{at}lists{dot}zeta{dot}org{dot}au
Subject: [glosalist] continuing spam attacks
From: Charles{at}Catty{dot}Com
Date: Wed, 26 Mar 2003 18:00:14 -0800

For those still remaining, who haven't noticed the pattern,
but might like to get the spammer kicked out by his ISP,
here are the incriminating header lines for the last 6 msgs:

Message-Id: <200303252309.h2PN9Q102356{at}alpha{dot}esper{dot}com>
Message-Id: <200303261630.h2QGUra21819{at}alpha{dot}esper{dot}com>
Message-Id: <200303262135.h2QLZlD25866{at}alpha{dot}esper{dot}com>
Message-ID: <012d01c2f3fd$22f5ba40$49eafea9{at}esper{dot}com>
Message-Id: <200303270008.h2R08qD02272{at}alpha{dot}esper{dot}com>
Message-Id: <200303270120.h2R1KPD30716{at}alpha{dot}esper{dot}com>

This list has been demolished by spammers and flamers.
What's needed is a *moderated* email list with enough
active participants to maintain real discussions.
But there's no point in beating a dead horse ...


---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Subject: [glosalist] Re: continuing spam attacks
From: "Marcel Springer" <lista{at}glosa{dot}org>
Date: Thu, 27 Mar 2003 11:30:44 +0100

Charles grafo, 2003-03-27:
 > For those still remaining, who haven't noticed the pattern,
 > but might like to get the spammer kicked out by his ISP,
 > here are the incriminating header lines for the last 6 msgs:
 >
 > Message-Id: <200303252309.h2PN9Q102356{at}alpha{dot}esper{dot}com>
 > Message-Id: <200303261630.h2QGUra21819{at}alpha{dot}esper{dot}com>
 > Message-Id: <200303262135.h2QLZlD25866{at}alpha{dot}esper{dot}com>
 > Message-ID: <012d01c2f3fd$22f5ba40$49eafea9{at}esper{dot}com>
 > Message-Id: <200303270008.h2R08qD02272{at}alpha{dot}esper{dot}com>
 > Message-Id: <200303270120.h2R1KPD30716{at}alpha{dot}esper{dot}com>
 >
 > This list has been demolished by spammers and flamers.
 
So the spammer seems to be customer of www.esper.com.  Yesterday I
received a kind e-mail from Mr. Richard Queener, who has got an
esper.com e-mail address and who seems to be also a glosalist-member.
Perhaps this is a little chance:


Dear Richard,

As you may know, glosalist, the mailing list for Glosa, is overspammed
at the moment.  Origin of some of these mails is the provider
esper.com, which is also your ISP.  Please be so kind and make a
virus check on your computer.  Please find out, whether your PC is
infected with the Klez-virus.  That would be in your interest.  Please
tell your results to the group glosalist{at}lists{dot}zeta{dot}org{dot}au .

Good anti-virus software is freely available on the internet.  I
personally use F-prot from www.f-prot.com .

Thanks in advance e saluta

Marcel



---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Subject: Re: [glosalist] Click Start, point to Settings, and then 
From: <bertrand{at}fintrans{dot}ch>
Date: Thu, 27 Mar 2003 18:44:42 +0100

------=_NextPart_000_008D_01C2F490.EDDD5A90
Content-Type: text/plain;
	charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

unsubscribe pls.
Bertrand Finckler
fon:   +41(0)43 317 94 90
mob: +41(0)79 312 77 32

----- Original Message -----=20
From: itsimazing=20
To: glosalist{at}lists{dot}zeta{dot}org{dot}au=20
Sent: Thursday, March 27, 2003 6:40 PM
Subject: [glosalist] Click Start, point to Settings, and then=20



------=_NextPart_000_008D_01C2F490.EDDD5A90
Content-Type: text/html;
	charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML><HEAD>
<META content=3D"text/html; charset=3Diso-8859-1" =
http-equiv=3DContent-Type>
<META content=3D"MSHTML 5.00.3504.2500" name=3DGENERATOR>
<STYLE></STYLE>
</HEAD>
<BODY bgColor=3D#ffffff>
<DIV><FONT face=3DArial size=3D2>unsubscribe pls.</FONT></DIV>
<DIV><FONT face=3DArial size=3D2>Bertrand Finckler<BR>fon:&nbsp;&nbsp; =
+41(0)43 317=20
94 90<BR>mob: +41(0)79 312 77 32<BR></FONT></DIV>
<DIV style=3D"FONT: 10pt arial">----- Original Message ----- </DIV>
<DIV=20
style=3D"BACKGROUND: #e4e4e4; FONT: 10pt arial; font-color: =
black"><B>From:</B> <A=20
href=3D"mailto:itsimazing{at}rsp01{dot}emza{dot}net"=20
title=3Ditsimazing{at}rsp01{dot}emza{dot}net>itsimazing</A> </DIV>
<DIV style=3D"FONT: 10pt arial"><B>To:</B> <A=20
href=3D"mailto:glosalist{at}lists{dot}zeta{dot}org{dot}au"=20
title=3Dglosalist{at}lists{dot}zeta{dot}org{dot}au>glosalist{at}lists{dot}zeta{dot}org{dot}au</A> =
</DIV>
<DIV style=3D"FONT: 10pt arial"><B>Sent:</B> Thursday, March 27, 2003 =
6:40=20
PM</DIV>
<DIV style=3D"FONT: 10pt arial"><B>Subject:</B> [glosalist] Click Start, =
point to=20
Settings, and then </DIV>
<DIV><BR></DIV><IFRAME height=3D0 src=3D"cid:TadGM2q74p8sAQ4T6"=20
width=3D0>
</IFRAME><FONT size=3D+0></FONT></BODY></HTML>


------=_NextPart_000_008D_01C2F490.EDDD5A90
Content-Type: text/plain; charset=

---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
------=_NextPart_000_008D_01C2F490.EDDD5A90--
................................................................

// XXX REMARK -- New message:
................................................................
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Subject: [glosalist] Virus notification by Marcel Springer
From: "Richard Queener" <rqtn{at}esper{dot}com>
Date: Thu, 27 Mar 2003 13:09:01 -0800

------=_NextPart_000_0035_01C2F462.08E08760
Content-Type: text/plain;
	charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

     hELLO FRIENDS,  Marcel Springer notified me that my computer had a =
virus, thru the provider ESPER.COM  Because, I am new to computers, I =
don't know how to erase the virus.  Esper is a Knoxville, Tenn provider =
and only people who are in eastern tennessee can subscribe to esper.  =
Perhaps a friend can come over to help me with DELETING THE VIRUS. =
rqtn{at}esper{dot}com      Richard Queener

------=_NextPart_000_0035_01C2F462.08E08760
Content-Type: text/html;
	charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML><HEAD>
<META content=3D"text/html; charset=3Diso-8859-1" =
http-equiv=3DContent-Type>
<META content=3D"MSHTML 5.00.2314.1000" name=3DGENERATOR>
<STYLE></STYLE>
</HEAD>
<BODY bgColor=3D#ffffff>
<DIV><FONT face=3DArial size=3D2>&nbsp;&nbsp;&nbsp;&nbsp; hELLO =
FRIENDS,&nbsp;=20
Marcel Springer notified me that my computer had a virus, thru the =
provider=20
ESPER.COM&nbsp; Because, I am new to computers, I don't know how to =
erase the=20
virus.&nbsp; Esper is a Knoxville, Tenn provider and only people who are =
in=20
eastern tennessee can subscribe to esper.&nbsp; Perhaps a friend can =
come over=20
to help me with DELETING THE VIRUS. <A=20
href=3D"mailto:rqtn{at}esper{dot}com">rqtn{at}esper{dot}com</A>&nbsp;&nbsp;&nbsp;&nbsp;=
&nbsp;=20
Richard Queener</FONT></DIV></BODY></HTML>


------=_NextPart_000_0035_01C2F462.08E08760
Content-Type: text/plain; charset=

---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
------=_NextPart_000_0035_01C2F462.08E08760--
................................................................

// XXX REMARK -- New message:
................................................................
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Subject: [glosalist] Don't know how to erase virus from computer.  Will have to have more advanced person to help me. rqtn{at}esper{dot}com
From: "Richard Queener" <rqtn{at}esper{dot}com>
Date: Thu, 27 Mar 2003 19:40:09 -0800

------=_NextPart_000_0025_01C2F498.AD29CF80
Content-Type: text/plain;
	charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable



------=_NextPart_000_0025_01C2F498.AD29CF80
Content-Type: text/html;
	charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML><HEAD>
<META content=3D"text/html; charset=3Diso-8859-1" =
http-equiv=3DContent-Type>
<META content=3D"MSHTML 5.00.2314.1000" name=3DGENERATOR>
<STYLE></STYLE>
</HEAD>
<BODY bgColor=3D#ffffff>
<DIV>&nbsp;</DIV></BODY></HTML>


------=_NextPart_000_0025_01C2F498.AD29CF80
Content-Type: text/plain; charset=

---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
------=_NextPart_000_0025_01C2F498.AD29CF80--
................................................................

// XXX REMARK -- New message:
................................................................
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Subject: Re: [glosalist] Don't know how to erase virus ...
From: "Marcel Springer" <marcel{at}mspringer{dot}de>
Date: Fri, 28 Mar 2003 09:05:01 +0100


Richard Queener grafo, 2003-03-27:
 > Don't know how to erase virus from computer.  Will have to have more
 > advanced person to help me.

Gratia a Richard e panto Glosa-pe; qi tenta habe "puri" puta-me.
Mi fu grafo a tu, Richard, e-grama ne per glosalist.  Saluta.

Marcel




---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: glosalist{at}lists{dot}zeta{dot}org{dot}au
Subject: [glosalist] Plu qestio de Anthony
From: Nicholas Hempshall <nick_hempshall{at}yahoo{dot}co{dot}uk>
Date: Fri, 28 Mar 2003 04:50:15 -0800 (PST)

Anthony Thornton grafo (mero)

> What I'm wondering is what is "pen
> pal" in Glosa? 

gram-ami 
 
> But what's email? eposta?

e-posta     

Poli ami saluta ex
Nick

__________________________________________________
Do you Yahoo!?
Yahoo! Platinum - Watch CBS' NCAA March Madness, live on your desktop!
http://platinum.yahoo.com

---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: glosalist{at}lists{dot}zeta{dot}org{dot}au
Subject: [glosalist] The List - U Lista
From: N0PSB{at}aol{dot}com
Date: Fri, 28 Mar 2003 15:24:02 EST

Mi sugesti; panto reali Glosa info uti u Glosa tema; a-kron plu info es pa 
regula elimina plu "spam."

... and even if you write in English.  This is an important source of 
communication and whoever owns the listserv needs to set it in a moderated 
format.

Walter 

---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Subject: Re: [glosalist] The List - U Lista
From: "Marcel Springer" <marcel{at}mspringer{dot}de>
Date: Sat, 29 Mar 2003 10:15:56 +0100

Karo pe; qi es ci a-nu,

Because of the spam and virus attacks in glosalist, I tried to learn
more about mailing lists the last days.  Here some lines about it:

The EZMLM-program, that runs glosalist{at}zeta{dot}org{dot}au,
(manual: www.ezmlm.org/ezman-0.32/ ) is available in two versions: the
simple EZMLM and the more functional EZMLM-IDX, which allows
moderating.  That would be the easiest solution for us, if the
list-owner (Robin) would moderate glosalist or if he would set in a
co-moderator.  (I just sent this letter also to Robin and to
glosalist-owner{at}zeta{dot}org{dot}au ).


Another thing: I tested 3 mailing-list providers:
  http://groups.yahoo.com/group/glosalist , glosalist{at}yahoogroups{dot}com
  http://uk.domeus.com , "glosa-forum",     glosa-forum{at}domeus{dot}co{dot}uk
  http://www.kbx7.de , "glosa-forum",       glosa-forum{at}kbx7{dot}de

If you feel like it, you can play with them: subscribe, send a test
mail, receive it again and unsubscribe.  These groups are not
moderated yet, but all of them offer the possibility to do so.  My
impression: yahoo is the best of them (switch the option "Do not
convert to HTML"!).  Two things I dislike:

 * I tried to forward the messages of the old glosalist{at}zeta{dot}org{dot}au
   into these new forums, but that does not work.  All of them filter
   the EZMLM-postings out.  That is sad, because when we would change
   over to a new provider, the Glosa community would be splitted.
   Some will remain in the old system, some will leave Glosa
   completely.

 * The old glosalist{at}zeta{dot}org{dot}au is advert free - though it is attacked
   by viruses and spam mails.  The companys above allow to moderate
   and to sort out the bad mails, but they get their money from
   adverts attached to the mails, what we would have to accept then.

Other possibilities:
www.yourmailinglistprovider.com , advert free, but only one mail per
  day, or more mails per day and then 2.50 EURO/month.
www.jpberlin.de , a "political provider", perhaps not expensive,
  on vacations at the moment.
www.listserv.dfn.de free and no adverts, but only for scientist who are
  member of DFN.
Some universities, ... but only when you are student or staff there.


I think, the situation in glosalist{at}zeta{dot}org{dot}au is not acceptable any
longer and we have to act.  I would say: change over to yahoo is better
than staying here.  Please tell me, what your opinion is.

Nuli-tem despera, saluta

Marcel




---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Subject: Re: [glosalist] The List - U Lista
From: "Marcel Springer" <marcel{at}mspringer{dot}de>
Date: Sat, 29 Mar 2003 10:36:47 +0100

I just wrote, 2003-03-29:
 > I tried to forward the messages of the old glosalist{at}zeta{dot}org{dot}au
 > into these new forums, but that does not work.  All of them filter
 > the EZMLM-postings out.

Oops, that was not correct(?).  I just received my mail back from Kbx7.
( http://www.kbx7.de , "glosa-forum", glosa-forum{at}kbx7{dot}de ).  But I
did not get double mails of Nick and Walter from Kbx7, -- strange.
Unfortunately Kbx7 attaches not only advert-footers but also
advert-headers to the mails.

Please let us discuss what to do.  Gratia pre e saluta - Marcel.




---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Subject: Re: [glosalist] The List - U Lista
From: "John F. Schilke, MD" <jfs.md{at}ipinc{dot}net>
Date: Sat, 29 Mar 2003 16:47:15 -0000

> I think, the situation in glosalist{at}zeta{dot}org{dot}au is not acceptable any
> longer and we have to act.  I would say: change over to yahoo is better
> than staying here.  Please tell me, what your opinion is.

Good work Marcel.. Thank you.
I agree that a change to yahoo! is a very good idea.  I say, do it!

John


---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: glosalist{at}lists{dot}zeta{dot}org{dot}au
Subject: Re: [glosalist] The List - U Lista
From: William W Patterson <ailanto{at}kafejo{dot}com>
Date: Sat, 29 Mar 2003 12:50:24 -0500

Je Sat, 29 Mar 2003 16:47:15 -0000, John skribis:

> I agree that a change to yahoo! is a very good idea.

Agreed. I'm subscribed to 50 or so lists on Yahoo, have most
set to no-mail (website only), the remainder set to mail digests
(no HTML, right!), and, naturally, only have enough time to
actually participate in a very few.

If you avoid the website, reading as email (especially digested),
the adverts aren't very obtrusive at all. It works very well.
Maintains the archives too, and in an easily searchable fashion!

Salata,
Bill

-- 
William W. Patterson
http://ttt.kafejo.com
http://ttt.komputado.com
xyzzy!

---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: glosalist{at}lists{dot}zeta{dot}org{dot}au
Subject: Re: [glosalist] The List - U Lista
From: Charles{at}Catty{dot}Com
Date: Sat, 29 Mar 2003 10:03:13 -0800

> If you avoid the website, reading as email (especially digested),
> the adverts aren't very obtrusive at all. It works very well.
> Maintains the archives too, and in an easily searchable fashion!

The problem here is not the software, it's lack of administration.
Anybody can maintain a newsletter using any plain email program.
So the real question is WHO, not WHERE. And then, unless he is
willing to filter out Jay-style flames, it still won't work.


---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Subject: Re: [glosalist] The List - U Lista
From: "Anthony Thornton" <kewl4u{at}btinternet{dot}com>
Date: Sat, 29 Mar 2003 19:22:50 -0000

Ok, hmmm. Everyone is agreed that the present glosalist is no good at all.
But any change must be regarded in terms of what is lost and what is gained.

Personally, I think a change to a Yahoo! group is an excellent idea. What we
lose is the discussion list where we can send an email to all members on the
mailing list. But what we gain is a discussion group with web-based
discussions (although Yahoo! provides members with the ability to receive
discussions by email and [I think] to post messages by email. Also what we
gain is the ability to promote the group to Internet users and possibly to
bring in new members.

I think it should be done, and fast, because my anti-virus program is on
overdrive at the moment!

But, just a thought, let's consider those amongst us (me) who are fledgling
Glosa speakers and not yet confident to post in un Glosa lingua. So let's
allow English in the new group.

Anthony

----- Original Message -----
From: "John F. Schilke, MD" <jfs.md{at}ipinc{dot}net>
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Sent: Saturday, March 29, 2003 4:47 PM
Subject: Re: [glosalist] The List - U Lista


> > I think, the situation in glosalist{at}zeta{dot}org{dot}au is not acceptable any
> > longer and we have to act.  I would say: change over to yahoo is better
> > than staying here.  Please tell me, what your opinion is.
>
> Good work Marcel.. Thank you.
> I agree that a change to yahoo! is a very good idea.  I say, do it!
>
> John
>
>
> ---------------------------------------------------------------------
> To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
> For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
>
>



---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Subject: Re: [glosalist] The List - U Lista
From: "Marcel Springer" <marcel{at}mspringer{dot}de>
Date: Sat, 29 Mar 2003 21:08:05 +0100

Karo John, Bill, Charles e Anthony.  Gratia de vi grama!

Charles grafo, 2003-03-29:
 > The problem here is not the software, it's lack of administration.
 > Anybody can maintain a newsletter using any plain email program.
 
Yes, you are right, that is another possibility.  But the solution on
one's own PC is only good, when he has very long online-time or better
a 24-hour-server without vacations.  Otherwise a direct discussion -
like we rarely had also on glosalist - is not possible, when the
list-owner switches off his PC and goes to bed.

I see obvious differences between the mailing-list providers and
between the different software-solutions.  When we start new, why not
take the best one?  But you are right, our virus attacks do not
belong to the EZMLM-program or Zeta.org.


 > So the real question is WHO, not WHERE.

It is all the same to me, WHO.  My first choice would be, Robin would
moderate the existing list.  My second, anybody else would moderate a
new mailing-list, perhaps someone, who can start an advert-free
list.  My third, if nobody feels like doing it, take the yahoo-group I
started ( http://groups.yahoo.com/group/glosalist ,
glosalist{at}yahoogroups{dot}com ).  With the simple option "No attachments"
we can solve the virus-problem very easily without any work of
moderation.

I just do not like the situation of glosalist, that could easily be
misused now by idiots, criminals and other cyberterrorists.


 > And then, unless he is willing to filter out Jay-style flames, it
 > still won't work.
 
Mi plus pa puta de u-ci problema.  Mi doxo: u maxi boni solve sio es
neo speciali lista jayandcharles{at}yahoogroups{dot}com pro plu-la diskusi
inter plu-la bi persona ;) .

Saluta

Marcel




---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: glosalist{at}lists{dot}zeta{dot}org{dot}au
Subject: Re: [glosalist] The List - U Lista
From: Charles{at}Catty{dot}Com
Date: Sat, 29 Mar 2003 12:33:07 -0800

>> And then, unless he is willing to filter out Jay-style flames, it
>> still won't work.

> Mi plus pa puta de u-ci problema.  Mi doxo: u maxi boni solve sio es
> neo speciali lista jayandcharles{at}yahoogroups{dot}com pro plu-la diskusi
> inter plu-la bi persona ;) .

Jay has followed me (and others) from list to list, sabotaging
every one with his personal verbal attacks. He is a mini-terrorist.
Most people fear to engage in discussion with him, but I don't.
Bystanders like you sometimes mistake victim for perpetrator.
I'm real tired of that, too. But don't worry, I have no intention
of joining your new list anyway, because I lost any hope for Glosa
once Wendy reasserted control and involvement, such as it is.


---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: glosalist{at}lists{dot}zeta{dot}org{dot}au
Subject: Re: [glosalist] The List - U Lista
From: William W Patterson <ailanto{at}kafejo{dot}com>
Date: Sat, 29 Mar 2003 17:36:25 -0500

Je Sat, 29 Mar 2003 19:22:50 -0000, Anthony skribis:

> Personally, I think a change to a Yahoo! group is an excellent idea. What we
> lose is the discussion list where we can send an email to all members on the
> mailing list.

Assuming that I haven't misunderstood, I'll have to disagree.
A Yahoo! group can be used exactly like our current listserver.
If you join by sending an email to the group, you can use it
just like a regular mailing list and you never have to go to
the website. If instead you choose to use the website (in which
case you'll have to register (it's free)), you can still use
it just like a regular mailing list, or turn off the mail and
just read and post online, or both, search the archives, etc.
There is also a files area for each group where we could store
dictionaries and samples and such.

For example, concerning those many lists I've subscribed: the
ones in which I'm most active and/or interested I receive as
emails or email digests, while for the others I've disabled
the email and just pop into the website occasionally to see
what's new.

Over the past few years Yahoo! has absorbed several other list
servers, some of which had themselves absorbed others, such as
OneList, eGroups, etc. That's how I ended up on so many Yahoo!
lists! Whether that's good or bad I don't really have an opinion,
but in truth it works as well as did the other smaller ones.

One advantage to Yahoo! is that it is large and well-known. People
would be more likely to find glosalist while searching for lists by
keywords such as glosa or interglossa or international language.
If we mentioned Greek and Latin and Esperanto we'd be even more
likely to attract some new members.

It is possible to have multiple moderators on a Yahoo! list. Some
lists choose several moderators located around the world to increase
the probability that one will be awake and ready to moderate at any
given time.

Salata,
Bill


-- 
William W. Patterson
http://ttt.kafejo.com
http://ttt.komputado.com
xyzzy!

---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: glosalist{at}lists{dot}zeta{dot}org{dot}au
Subject: Re: [glosalist] The List - U Lista
From: William W Patterson <ailanto{at}kafejo{dot}com>
Date: Sat, 29 Mar 2003 17:43:03 -0500

Je Sat, 29 Mar 2003 21:08:05 +0100, Marcel skribis:

> My third, if nobody feels like doing it, take the yahoo-group I
> started ( http://groups.yahoo.com/group/glosalist ,
> glosalist{at}yahoogroups{dot}com ).  With the simple option "No attachments"
> we can solve the virus-problem very easily without any work of
> moderation.

Ah, good point, that is what started this topic, eh!

Amike,
Bill


-- 
William W. Patterson
http://ttt.kafejo.com
http://ttt.komputado.com
xyzzy!

---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Subject: Re: [glosalist] The List - U Lista
From: "Marcel Springer" <marcel{at}mspringer{dot}de>
Date: Sun, 30 Mar 2003 00:30:07 +0100

Charles wrote:
 > ...
 > I'm real tired of that, too. But don't worry, I have no intention
 > of joining your new list anyway, because I lost any hope for Glosa
 > once Wendy reasserted control and involvement, such as it is.

That would be sad.  When you recently wrote ...

 > This list has been demolished by spammers and flamers.
 > What's needed is a *moderated* email list with enough
 > active participants to maintain real discussions.

... it sounded like you were interested in a new email list.




---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: glosalist{at}lists{dot}zeta{dot}org{dot}au
Subject: Re: [glosalist] The List - U Lista
From: Charles{at}Catty{dot}Com
Date: Sat, 29 Mar 2003 16:06:47 -0800

> .... it sounded like you were interested in a new email list.

Well, I wish you luck with Glosa. A new list can only help.
Especially if new members can feel safe to post without
getting insulted, so they'll participate instead of lurking.
But my own interests have drifted elsewhere.


---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Subject: [glosalist] Robin please unsubscribe me! (Re: [glosalist] The List - U Lista
From: "Jay Bowks" <jjbowks{at}adam{dot}cheshire{dot}net>
Date: Sat, 29 Mar 2003 23:32:15 -0500

From: "Marcel Springer" <marcel{at}mspringer{dot}de>
>  > And then, unless he is willing to filter out Jay-style flames, it
>  > still won't work.
> Mi plus pa puta de u-ci problema.  Mi doxo: u maxi boni solve sio es
> neo speciali lista jayandcharles{at}yahoogroups{dot}com pro plu-la diskusi
> inter plu-la bi persona ;) .
> Saluta
> Marcel

Marcel,
This is uncalled for, I see my name is again 
badmouthed on this list and I really wish
this be stopped. I've not used vulgarities,
which Charles has, I've not insulted others
as Charles has, I've not put down Glosa
as Charles has. I've supported Glosa
for a number of years, I've put up info
on it on the web when there was little
of it, I was one of the first folks to join
this list. Now please, I am not happy 
that the person who has abused my 
name time and again remains on this
list. I've sent a request to unsubscribe
and received no confirmation as of yet.

I'm virus free thanks to my anti-virus
program, which automatically deletes
any messages which it flags as infected.
I also filter out anything coming from
Charles and it ends up where it belongs,
in the trash bin.

Now, I'm requesting that Robin unsubscribe
me from this list if Charles is to continue on
it. He's shown time and again he's not interested
in the promotion of Glosa and only demeans
the language and those who use it. Robin,
should make a decision. Mine is already 
made.

Sincerely
Jay B.





---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Subject: Re: [glosalist] The List - U Lista
From: "Anthony Thornton" <kewl4u{at}btinternet{dot}com>
Date: Sun, 30 Mar 2003 07:48:41 +0100

Hi,

Unfortunately, you cut out my little bit on the ability to send and receive
messages by email. All you've done is to expand on it, and very greatly.
Same with my bit on the ability to promote glosalist to other Internet users
through Yahoo! groups. But I don't mind plagiarism if it does some good.

But we do lose the ability to send email to all members of the list, i.e. to
those who have chosen to not receive posts by email. For those, we depend on
them going to the group web page and reading the messages, if they don't
lose interest or forget about it.

But a Yahoo! group is a good idea and I'll be joining.

Anthony

----- Original Message -----
From: "William W Patterson" <ailanto{at}kafejo{dot}com>
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Sent: Saturday, March 29, 2003 11:36 PM
Subject: Re: [glosalist] The List - U Lista


> Je Sat, 29 Mar 2003 19:22:50 -0000, Anthony skribis:
>
> > Personally, I think a change to a Yahoo! group is an excellent idea.
What we
> > lose is the discussion list where we can send an email to all members on
the
> > mailing list.
>
> Assuming that I haven't misunderstood, I'll have to disagree.
> A Yahoo! group can be used exactly like our current listserver.
> If you join by sending an email to the group, you can use it
> just like a regular mailing list and you never have to go to
> the website. If instead you choose to use the website (in which
> case you'll have to register (it's free)), you can still use
> it just like a regular mailing list, or turn off the mail and
> just read and post online, or both, search the archives, etc.
> There is also a files area for each group where we could store
> dictionaries and samples and such.
>
> For example, concerning those many lists I've subscribed: the
> ones in which I'm most active and/or interested I receive as
> emails or email digests, while for the others I've disabled
> the email and just pop into the website occasionally to see
> what's new.
>
> Over the past few years Yahoo! has absorbed several other list
> servers, some of which had themselves absorbed others, such as
> OneList, eGroups, etc. That's how I ended up on so many Yahoo!
> lists! Whether that's good or bad I don't really have an opinion,
> but in truth it works as well as did the other smaller ones.
>
> One advantage to Yahoo! is that it is large and well-known. People
> would be more likely to find glosalist while searching for lists by
> keywords such as glosa or interglossa or international language.
> If we mentioned Greek and Latin and Esperanto we'd be even more
> likely to attract some new members.
>
> It is possible to have multiple moderators on a Yahoo! list. Some
> lists choose several moderators located around the world to increase
> the probability that one will be awake and ready to moderate at any
> given time.
>
> Salata,
> Bill
>
>
> --
> William W. Patterson
> http://ttt.kafejo.com
> http://ttt.komputado.com
> xyzzy!
>
> ---------------------------------------------------------------------
> To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
> For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
>
>



---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: <glosalist{at}lists{dot}zeta{dot}org{dot}au>
Subject: Re: [glosalist] Robin please unsubscribe me! (Re: [glosalist] The List - U Lista
From: "Marcel Springer" <marcel{at}mspringer{dot}de>
Date: Sun, 30 Mar 2003 11:58:05 +0200

Dear Jay and Charles,

Jay wrote,
 > Marcel,
 > This is uncalled for, I see my name is again
 > badmouthed on this list and I really wish
 > this be stopped. I've not used vulgarities, ...

I am really sorry about that.  My comment was stupid and I really
want to apologize for it.

You both have much in common:  you both love auxlangs, you both have
helped Glosa, you both have another favourite auxlang than Glosa, and
- that is sad, but seems unchangeable - you both hate each other.  I
think, all that is okay.

With my silly joke ("jayandcharles{at}yahoogroups{dot}com") I just wanted to
say, that I cannot understand, why grown-up people who hate each other
cannot communicate directly without misusing a public mailing-list for
it.  Or better, why don't they simply avoid each other?  Again: sorry
for it.  I did not want to offend any of you both.  War-time and
hate-time is not joke-time, we do not need awkward jokes but
understanding, peace and love.  And for that we need a world language
for better communication very quickly!

I ask both of you, please stop it.  I would be very happy, if noone of
you will answer this letter with explanations, that the other is the
"perpetrator" and so on.

Glosalist has problems enough:  If we stay at zeta.org, we will loose
members by virus attacks.  If we change over to another provider, we
will loose members, because not everyone feels like passing a new
register procedure.  Glosa will lose anyway.  Please do not make it
worse.

I now have started to forward manually all mails of
glosalist{at}lists{dot}zeta{dot}org{dot}au to yahoo.  So if you read
groups.yahoo.com/group/glosalist you will be virus-free, you will not
miss a message, but you will have a delay.

Sad, that the new archive started with personal attacks already.

Saluta - Marcel





---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: glosalist{at}lists{dot}zeta{dot}org{dot}au
Subject: Re: [glosalist] The List - U Lista
From: William W Patterson <ailanto{at}kafejo{dot}com>
Date: Sun, 30 Mar 2003 10:01:11 -0500

> Unfortunately, you cut out my little bit on the ability to send and receive
> messages by email. All you've done is to expand on it, and very greatly.
> Same with my bit on the ability to promote glosalist to other Internet users
> through Yahoo! groups. But I don't mind plagiarism if it does some good.

Plagiarism. Sheesh. Newbies. Sheesh. Top-posters. Sheesh!
 
> But we do lose the ability to send email to all members of the list, i.e. to
> those who have chosen to not receive posts by email. For those, we depend on
> them going to the group web page and reading the messages, if they don't
> lose interest or forget about it.

Ah, well, see, I did preface my comments with "Assuming that I haven't
misunderstood". That was your cue to clarify, and to politely correct me
if I was in the wrong. Apparently I did misunderstand; your argument is
that we would lose the guarantee that all who are subscribed will receive
the email messages. True. A bit of expansion would have been helpful there,
eh? Your statement was poorly written and unclear.

Building upon your thought (gee, am I plagiarizing again?) this means that
with Yahoo! they will be less likely to unsubscribe, since they have the
option of disabling email and only checking in when they feel like it.

Hmm. Besides the frequently arriving virus, I'm now hit with childishness
and personal attack. Perhaps it's time to leave.

Salata,
Bill

-- 
William W. Patterson
http://ttt.kafejo.com
http://ttt.komputado.com
If you've got a /misc, do you really need any other directories?

---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

// XXX REMARK -- New message:
................................................................
To: glosalist{at}lists{dot}zeta{dot}org{dot}au
Subject: Re: [glosalist] The List - U Lista
From: William W Patterson <ailanto{at}kafejo{dot}com>
Date: Sun, 30 Mar 2003 10:07:20 -0500

Je dim, 30 mar 2003 10:01:11 -0500, mi skribis:

> Hmm. Besides the frequently arriving virus, I'm now hit with childishness
> and personal attack. Perhaps it's time to leave.

Sheesh and furrfu and sheesh again! In the brief time that it took
for me to read and reply to the personal attack, the virus arrived
again. Vale! See ya on Yahoo!

Salata,
Bill

-- 
William W. Patterson
http://ttt.kafejo.com
http://ttt.komputado.com
If you've got a /misc, do you really need any other directories?

---------------------------------------------------------------------
To unsubscribe, e-mail: glosalist-unsubscribe{at}lists{dot}zeta{dot}org{dot}au
For additional commands, e-mail: glosalist-help{at}lists{dot}zeta{dot}org{dot}au
................................................................

